services:
  nut-upsd:
    container_name: nut-upsd
    image: instantlinux/nut-upsd
    networks:
      - localprom
    environment:
      - TZ=Europe/Copenhagen
      # Driver found with this tool https://networkupstools.org/stable-hcl.html
      - DRIVER=usbhid-ups
    devices:
      # Only pinning to the bus as the device number can change
      - /dev/bus/usb/001:/dev/bus/usb/001
    ports:
      - "3493:3493"
    secrets:
      - nut-upsd-password
    restart: unless-stopped
  
  nut-exporter:
    image: hon95/prometheus-nut-exporter:1
    container_name: nut-exporter
    networks:
      - localprom
    environment:
      - TZ=Europe/Copnehagen
      - HTTP_PATH=/metrics
    ports:
      - "9995:9995"
    depends_on:
      - nut-upsd
    restart: unless-stopped

secrets:
  nut-upsd-password:
    # Place this where you like, but you may want to read up on securing password files: https://docs.docker.com/compose/use-secrets/
    file: ./secrets/nut-upsd-password

networks:
  localprom:
    name: prometheus_localprom
    external: true
  